[build]
target = "thumbv4t-none-eabi"

[target.thumbv4t-none-eabi]
runner = "mgba"
rustflags = [
    "-Clink-arg=-Tgba.ld",
    "-Ctarget-cpu=arm7tdmi",
    "-Cforce-frame-pointers=yes",
]

[target.armv4t-none-eabi]
runner = "mgba"
rustflags = [
    "-Clink-arg=-Tgba.ld",
    "-Ctarget-cpu=arm7tdmi",
    "-Cforce-frame-pointers=yes",
]

[unstable]
build-std = ["alloc", "core"]
build-std-features = ["compiler-builtins-mem"]
